SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS BOX_OFFICE;




/* Create Tables */

CREATE TABLE BOX_OFFICE
(
	RANK int(11) NOT NULL,
	MOVIE_NM varchar(300) NOT NULL,
	MOVIE_CD varchar(10) NOT NULL,
	RANK_INTEN int(11) NOT NULL,
	RANK_OLD_AND_NEW char(3) NOT NULL,
	OPEN_DT char(10) NOT NULL,
	SALES_AMT bigint(20) NOT NULL,
	SALES_SHARE float NOT NULL,
	SALES_INTEN bigint(20) NOT NULL,
	SALES_CHANGE float NOT NULL,
	SALES_ACC bigint(20) NOT NULL,
	AUDI_CNT int NOT NULL,
	AUDI_INTEN int NOT NULL,
	AUDI_CHANGE float NOT NULL,
	AUDI_ACC int NOT NULL,
	SCRN_CNT int NOT NULL,
	SHOW_CNT int NOT NULL,
	TARGET_DT char(8) NOT NULL,
	PRIMARY KEY (RANK, TARGET_DT)
);



