SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS ACTOR_EVALUATION;
DROP TABLE IF EXISTS GENRE_INFO;
DROP TABLE IF EXISTS MOVIE_GENRE;
DROP TABLE IF EXISTS MOVIE_REVIEW;
DROP TABLE IF EXISTS USER_EVALUATION;
DROP TABLE IF EXISTS MOVIE_INFO;
DROP TABLE IF EXISTS PERSON_FILMOGRAPHY;
DROP TABLE IF EXISTS PERSON_INFO;
DROP TABLE IF EXISTS USER_INFO;




/* Create Tables */

CREATE TABLE ACTOR_EVALUATION
(
	PI_ID int NOT NULL,
	UI_NUM int NOT NULL,
	AE_THUMBS_UP char(1) NOT NULL,
	PRIMARY KEY (PI_ID, UI_NUM)
);


CREATE TABLE GENRE_INFO
(
	ID int NOT NULL,
	GENRE_ID int NOT NULL
);


CREATE TABLE MOVIE_GENRE
(
	GENRE_ID int NOT NULL,
	NAME char(6) NOT NULL,
	PRIMARY KEY (GENRE_ID)
);


CREATE TABLE MOVIE_INFO
(
	ID int NOT NULL AUTO_INCREMENT,
	TITLE varchar(50) NOT NULL,
	ADULT char(5) NOT NULL,
	ORIGINAL_TITLE varchar(80) NOT NULL,
	OVERVIEW text NOT NULL,
	POPULARITY float NOT NULL,
	RELEASE_DATE text NOT NULL,
	VOTE_AVERAGE float NOT NULL,
	VOTE_COUNT int NOT NULL,
	POSTER_PATH text NOT NULL,
	BACKDROP_PATH text,
	PRIMARY KEY (ID)
);


CREATE TABLE MOVIE_REVIEW
(
	MR_NUM int NOT NULL AUTO_INCREMENT,
	MR_CONTENT text NOT NULL,
	CREDAT datetime NOT NULL,
	CRETIM datetime NOT NULL,
	LMODAT datetime NOT NULL,
	LMOTIM datetime NOT NULL,
	UI_NUM int NOT NULL,
	ID int NOT NULL,
	PRIMARY KEY (MR_NUM),
	UNIQUE (MR_NUM),
	UNIQUE (UI_NUM, ID)
);


CREATE TABLE PERSON_FILMOGRAPHY
(
	PF_ID int NOT NULL,
	PF_TITLE varchar(20),
	PF_ORIGINAL_TITLE varchar(80),
	PF_OVERVIEW text,
	PF_POSTER_PATH text,
	PF_RELEASE_DATE varchar(20),
	PF_CHARACTER varchar(20),
	PI_ID int NOT NULL,
	PRIMARY KEY (PF_ID, PI_ID)
);


CREATE TABLE PERSON_INFO
(
	PI_ID int NOT NULL,
	PI_BIOGRAPHY text,
	PI_BIRTHDAY varchar(20),
	PI_GENDER int,
	PI_HOMEPAGE varchar(80),
	PI_PLACE_OF_BIRTH varchar(70),
	PI_PROFILE_PATH text,
	PI_NAME varchar(20),
	PRIMARY KEY (PI_ID)
);


CREATE TABLE USER_EVALUATION
(
	UI_NUM int NOT NULL,
	ID int NOT NULL,
	UE_THUMBS_UP char(1),
	PRIMARY KEY (UI_NUM, ID)
);


CREATE TABLE USER_INFO
(
	UI_NUM int NOT NULL AUTO_INCREMENT,
	UI_ID varchar(30) NOT NULL,
	UI_NICKNAME varchar(50) NOT NULL,
	UI_PWD varchar(70) NOT NULL,
	UI_EMAIL varchar(50) NOT NULL,
	PRIMARY KEY (UI_NUM),
	UNIQUE (UI_ID)
);



/* Create Foreign Keys */

ALTER TABLE GENRE_INFO
	ADD FOREIGN KEY (GENRE_ID)
	REFERENCES MOVIE_GENRE (GENRE_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE GENRE_INFO
	ADD FOREIGN KEY (ID)
	REFERENCES MOVIE_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOVIE_REVIEW
	ADD FOREIGN KEY (ID)
	REFERENCES MOVIE_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_EVALUATION
	ADD FOREIGN KEY (ID)
	REFERENCES MOVIE_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ACTOR_EVALUATION
	ADD FOREIGN KEY (PI_ID)
	REFERENCES PERSON_INFO (PI_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PERSON_FILMOGRAPHY
	ADD FOREIGN KEY (PI_ID)
	REFERENCES PERSON_INFO (PI_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ACTOR_EVALUATION
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MOVIE_REVIEW
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USER_EVALUATION
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



