SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS MOVIE_REVIEW;
DROP TABLE IF EXISTS USER_INFO;




/* Create Tables */

CREATE TABLE MOVIE_REVIEW
(
	MR_NUM int NOT NULL AUTO_INCREMENT,
	MR_CONTENT text NOT NULL,
	CREDAT datetime NOT NULL,
	CRETIM datetime NOT NULL,
	LMODAT datetime NOT NULL,
	LMOTIM datetime NOT NULL,
	UI_NUM int NOT NULL,
	PRIMARY KEY (MR_NUM),
	UNIQUE (MR_NUM)
);


CREATE TABLE USER_INFO
(
	UI_NUM int NOT NULL AUTO_INCREMENT,
	UI_ID varchar(30) NOT NULL,
	UI_NICKNAME varchar(50) NOT NULL,
	UI_PWD varchar(70) NOT NULL,
	UI_EMAIL varchar(50) NOT NULL,
	PRIMARY KEY (UI_NUM),
	UNIQUE (UI_ID)
);



/* Create Foreign Keys */

ALTER TABLE MOVIE_REVIEW
	ADD FOREIGN KEY (UI_NUM)
	REFERENCES USER_INFO (UI_NUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



